apiVersion: v1
kind: Pod
metadata:
 name: ekampod1   # lower case char
 labels:
  x: hello   # key : value 

spec:
 containers:
  - image: nginx  #  this will be pulled from Docker hub
    name: ekampod1   # optional field 
    ports:   # optional field  
     - containerPort: 80  #  same as expose in Dockerfile
